 CREATE DATABASE DATABASEVOLUNTARIADO2
GO
USE DATABASEVOLUNTARIADO2

USE MASTER
DROP DATABASE DATABASEVOLUNTARIADO



CREATE TABLE ALUMNADO_INSCRITO (
    DNI NVARCHAR(9) PRIMARY KEY,
    NOMBRE NVARCHAR(25) NOT NULL,
    PRIMER_APELLIDO NVARCHAR(25) NOT NULL,
    SEGUNDO_APELLIDO NVARCHAR(25) NOT NULL,
    CORREO_ELECTRONICO NVARCHAR(25) NOT NULL,
    TELEFONO NVARCHAR(9) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL CHECK (FECHA_NACIMIENTO<GETDATE()),
    NOMBRE_CURSO NVARCHAR(10) NOT NULL
)



CREATE TABLE ACTIVIDADES (
    IDPROYECTO SMALLINT, -- FOREIGN KEY + PRIMARY KEY
	IDACTIVIDAD SMALLINT, -- PRIMARY KEY
    NOMBRE NVARCHAR(25) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    UBICACION NVARCHAR(255) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE,
	PRIMARY KEY (IDPROYECTO, IDACTIVIDAD)
)


CREATE TABLE ALUMNO_ACTIVIDAD ( -- TODO FOREIGN KEY + PRIMARY KEY
    DNI NVARCHAR(9), 
    IDPROYECTO SMALLINT,
	IDACTIVIDAD SMALLINT,
	PRIMARY KEY (DNI, IDPROYECTO, IDACTIVIDAD)
)



--IKER
CREATE TABLE PROYECTOS_TIPOS(
IDPROYECTO SMALLINT,--AÑADIR PRIMARY KEYS, ES CLAVE COMPUESTA POR LOS DOS CAMPOS
NOMBRE_TIPO NVARCHAR(25)
PRIMARY KEY (IDPROYECTO, NOMBRE_TIPO)
)


CREATE TABLE PROYECTO_ODS(
IDPROYECTO SMALLINT,--AÑADIR PRIMARY KEYS, ES CLAVE COMPUESTA POR LOS DOS CAMPOS
IDODS SMALLINT
PRIMARY KEY (IDPROYECTO, IDODS)
)

CREATE TABLE TIPO(
NOMBRE NVARCHAR(25) PRIMARY KEY
)


CREATE TABLE PROYECTOS(
IDPROYECTO SMALLINT PRIMARY KEY,
NOMBRE_PROYECTO NVARCHAR(25) NOT NULL,
DESCRIPCION NVARCHAR(40) NULL,
FECHA_INICIO DATETIME NOT NULL,
FECHA_FIN DATETIME, -- CHECK (FECHA_FIN>FECHA_INICIO)
ESTADO BIT NOT NULL,
IDORGANIZACION SMALLINT NOT NULL,
CIF_ORG NVARCHAR(9) NOT NULL -- FOREIGN KEY REFERENCES ORGANIZACIONES(CIF)
)




--DAVID

CREATE TABLE ODS(
IDODS SMALLINT PRIMARY KEY,
NOMBRE NVARCHAR(50) NOT NULL,
DESCRIPCION TEXT NOT NULL,
)


CREATE TABLE ORGANIZACIONES(
IDORGANIZACION SMALLINT IDENTITY(1,1), -- PRIMARY KEY ID+CIF
CIF NVARCHAR(9),
NOMBRE NVARCHAR(25) NOT NULL,
DIRECCION NVARCHAR(255) NOT NULL,
TELEFONO CHAR(9) NOT NULL,
CORREO NVARCHAR(25) NOT NULL
PRIMARY KEY (IDORGANIZACION, CIF)
)



CREATE TABLE CURSOS(
NOMBRE NVARCHAR(10) PRIMARY KEY,
)






--LAURA
CREATE TABLE ALUMNO_TIPO (
DNI NVARCHAR(9),
NOMBRE_TIPO NVARCHAR(25)
PRIMARY KEY (DNI, NOMBRE_TIPO)
)


CREATE TABLE HORARIO ( 
IDHORARIO INT IDENTITY(1,1), --PK ID+DNI
DNI NVARCHAR(9),
DIA_SEMANA NVARCHAR(10) NOT NULL,
HORA_INICIO DATETIME NOT NULL,
HORA_FIN DATETIME NOT NULL
PRIMARY KEY (IDHORARIO, DNI)
)



ALTER TABLE ALUMNADO_INSCRITO
ADD CONSTRAINT FK_ALUMNADO_CURSOS FOREIGN KEY (NOMBRE_CURSO)
REFERENCES CURSOS(NOMBRE)

ALTER TABLE ACTIVIDADES
ADD CONSTRAINT FK_ACTIVIDADES_PROYECYOS FOREIGN KEY (IDPROYECTO)
REFERENCES PROYECTOS(IDPROYECTO)

ALTER TABLE ALUMNO_ACTIVIDAD
ADD CONSTRAINT FK_ALUMNOACTIVIDAD_ALUMNADO FOREIGN KEY (DNI)
REFERENCES ALUMNADO_INSCRITO(DNI)

ALTER TABLE ALUMNO_ACTIVIDAD
ADD CONSTRAINT FK_ALUMNOACTIVIDAD_PROYECTOS FOREIGN KEY (IDPROYECTO, IDACTIVIDAD)
REFERENCES ACTIVIDADES(IDPROYECTO, IDACTIVIDAD)

ALTER TABLE PROYECTOS_TIPOS
ADD CONSTRAINT FK_PROYECTOS_TIPOS_PROYECTOS
FOREIGN KEY (IDPROYECTO) REFERENCES PROYECTOS(IDPROYECTO)

ALTER TABLE PROYECTOS_TIPOS
ADD CONSTRAINT FK_PROYECTOS_TIPOS_TIPO
FOREIGN KEY (NOMBRE_TIPO) REFERENCES TIPO(NOMBRE)

ALTER TABLE PROYECTO_ODS 
ADD CONSTRAINT FK_PROYECTO_ODS_ODS 
FOREIGN KEY (IDODS) REFERENCES ODS(IDODS)

ALTER TABLE PROYECTO_ODS 
ADD CONSTRAINT FK_PROYECTO_ODS_PROYECTO
FOREIGN KEY (IDPROYECTO) REFERENCES PROYECTOS(IDPROYECTO)

ALTER TABLE PROYECTOS
ADD CONSTRAINT FK_PROYECTOS_CIF
FOREIGN KEY (IDORGANIZACION, CIF_ORG) REFERENCES ORGANIZACIONES(IDORGANIZACION, CIF)

ALTER TABLE ALUMNO_TIPO
ADD CONSTRAINT FK_ALUMNO_TIPO_DNI
FOREIGN KEY (DNI) REFERENCES ALUMNADO_INSCRITO(DNI)

ALTER TABLE ALUMNO_TIPO
ADD CONSTRAINT FK_ALUMNO_TIPO_TIPO
FOREIGN KEY (NOMBRE_TIPO) REFERENCES TIPO(NOMBRE)

ALTER TABLE HORARIO 
ADD CONSTRAINT FK_HORARIO_DNI
FOREIGN KEY (DNI) REFERENCES ALUMNADO_INSCRITO(DNI)



--CREAR ÍNDICES PARA EL NOMBRE, APELLIDO1 Y APELLIDO2
CREATE INDEX IX_N_A_A ON ALUMNADO_INSCRITO (NOMBRE,PRIMER_APELLIDO, SEGUNDO_APELLIDO)

--OTROS ÍNDICES
CREATE INDEX IX_ALUMNADO_CORREO ON ALUMNADO_INSCRITO(CORREO_ELECTRONICO)
CREATE INDEX IX_PROYECTOS_ESTADO ON PROYECTOS(ESTADO)
CREATE INDEX IX_ACTIVIDADES_NOMBRE ON ACTIVIDADES(NOMBRE)
CREATE INDEX IX_ORGANIZACIONES_NOMBRE ON ORGANIZACIONES(NOMBRE)

--REGLA PARA EL DNI 
-- REGLA PARA EL DNI
GO
CREATE RULE DNIS AS 
    @CAMPO LIKE '[A-Z][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
GO
EXEC SP_BINDRULE DNIS, 'dbo.ALUMNO_TIPO.DNI'
EXEC SP_BINDRULE DNIS, 'dbo.HORARIO.DNI'
EXEC SP_BINDRULE DNIS, 'dbo.ALUMNADO_INSCRITO.DNI'
EXEC SP_BINDRULE DNIS, 'dbo.ALUMNO_ACTIVIDAD.DNI'
GO

-- REGLA PARA EL TELÉFONO (Sólo acepta móviles que empiezan por 6 o 7)
GO
CREATE RULE TELEFONO AS 
    @CAMPO LIKE '[6-7][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
GO
EXEC SP_BINDRULE TELEFONO, 'dbo.ALUMNADO_INSCRITO.TELEFONO'
EXEC SP_BINDRULE TELEFONO, 'dbo.ORGANIZACIONES.TELEFONO'
GO

-- VALIDACIÓN DEL CORREO CON CHECK CONSTRAINT (No con RULE)
ALTER TABLE dbo.ALUMNADO_INSCRITO
ADD CONSTRAINT CK_CORREO_INSCRITO 
CHECK (CORREO_ELECTRONICO LIKE '%@%.%');

ALTER TABLE dbo.ORGANIZACIONES
ADD CONSTRAINT CK_CORREO_ORGANIZACIONES 
CHECK (CORREO LIKE '%@%.%');
GO



--FECHAS Y HORAS
ALTER TABLE PROYECTOS 
ADD CONSTRAINT CK_PROYECTOS_FECHAS CHECK (FECHA_FIN IS NULL OR FECHA_FIN > FECHA_INICIO)

ALTER TABLE ACTIVIDADES 
ADD CONSTRAINT CK_ACTIVIDADES_FECHAS CHECK (FECHA_FIN IS NULL OR FECHA_FIN > FECHA_INICIO)

ALTER TABLE HORARIO 
ADD CONSTRAINT CK_HORARIO_HORAS CHECK (HORA_FIN > HORA_INICIO)

INSERT INTO ALUMNADO_INSCRITO VALUES ('12345678A','Sergio','De la Fuente','Marco','sergio4vientos@gmail.com','123456789','2003-12-17','1DAM')
INSERT INTO ALUMNADO_INSCRITO VALUES ('87654321B','Iker','Aramendia','Marco','ikeraramendia@gmail.com','987654321','2002-01-01','1TLA')
INSERT INTO ALUMNADO_INSCRITO VALUES ('23456789C','David','Martin','Marco','davidmartin@gmail.com','147258369','2006-02-02','2ASIR')
INSERT INTO ALUMNADO_INSCRITO VALUES ('98765432D','Laura','Felix','Marco','laurafelix@gmail.com','963852741','1999-03-03','2TLB')

INSERT INTO ALUMNO_ACTIVIDAD VALUES ('12345678A',1,1)
INSERT INTO ALUMNO_ACTIVIDAD VALUES ('87654321B',1,2)
INSERT INTO ALUMNO_ACTIVIDAD VALUES ('23456789C',2,1)
INSERT INTO ALUMNO_ACTIVIDAD VALUES ('98765432D',2,2)

INSERT INTO TIPO VALUES ('Voluntariado Social');
INSERT INTO TIPO VALUES ('Voluntariado Ambiental');
INSERT INTO TIPO VALUES ('Voluntariado Educativo');
INSERT INTO TIPO VALUES ('Voluntariado Cultural');
INSERT INTO TIPO VALUES ('Voluntariado Deportivo');
INSERT INTO TIPO VALUES ('Voluntariado en Salud');
INSERT INTO TIPO VALUES ('Voluntariado Digital');

INSERT INTO ODS VALUES (1,'Fin de la pobreza','Erradicar la pobreza extrema en todas sus formas y en todo el mundo.')
INSERT INTO ODS VALUES (2,'Hambre cero','Garantizar el acceso a alimentos nutritivos y acabar con la desnutrición.')
INSERT INTO ODS VALUES (3,'Salud y bienestar','Asegurar una vida saludable y promover el bienestar para todos.')
INSERT INTO ODS VALUES (4,'Educación de calidad','Garantizar una educación inclusiva y equitativa para todos.')
INSERT INTO ODS VALUES (5,'Igualdad de género','Eliminar la discriminación y la violencia contra las mujeres y niñas.')
INSERT INTO ODS VALUES (6,'Agua limpia y saneamiento','Asegurar el acceso universal al agua potable y saneamiento.')
INSERT INTO ODS VALUES (7,'Energía asequible y no contaminante','Promover el acceso a energía sostenible y renovable.')
INSERT INTO ODS VALUES (8,'Trabajo decente y crecimiento económico','Fomentar empleos dignos y un desarrollo económico sostenible')
INSERT INTO ODS VALUES (9,'Industria, innovación e infraestructura',' Impulsar infraestructuras resilientes y tecnologías innovadoras.')
INSERT INTO ODS VALUES (10,'Reducción de las desigualdades','Disminuir la brecha económica y social dentro y entre los países.')
INSERT INTO ODS VALUES (11,'Ciudades y comunidades sostenibles','Crear ciudades inclusivas, seguras y sostenibles.')
INSERT INTO ODS VALUES (12,'Producción y consumo responsables','Fomentar el uso eficiente de los recursos y reducir los desechos.')
INSERT INTO ODS VALUES (13,'Acción por el clima','omar medidas urgentes para combatir el cambio climático.')
INSERT INTO ODS VALUES (14,'Vida submarina','Proteger los océanos y la biodiversidad marina.')
INSERT INTO ODS VALUES (15,'Vida de ecosistemas terrestres','Conservar bosques y detener la pérdida de biodiversidad.')
INSERT INTO ODS VALUES (16,'Paz, justicia e instituciones sólidas','Promover sociedades pacíficas y acceso a la justicia.')
INSERT INTO ODS VALUES (17,'Alianzas para lograr los objetivos','Fortalecer la cooperación global para alcanzar los ODS.')

INSERT INTO CURSOS VALUES ('1TLA');
INSERT INTO CURSOS VALUES ('1TLB');
INSERT INTO CURSOS VALUES ('1CI');
INSERT INTO CURSOS VALUES ('1DAM');
INSERT INTO CURSOS VALUES ('1GVEC');
INSERT INTO CURSOS VALUES ('1ASIR');
INSERT INTO CURSOS VALUES ('1AF');
INSERT INTO CURSOS VALUES ('2TLA');
INSERT INTO CURSOS VALUES ('2TLB');
INSERT INTO CURSOS VALUES ('2CI');
INSERT INTO CURSOS VALUES ('2DAM');
INSERT INTO CURSOS VALUES ('2GVEC');
INSERT INTO CURSOS VALUES ('2ASIR');
INSERT INTO CURSOS VALUES ('2AF');
